name: .NET Core

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore src/MongrationDotNet/MongrationDotNet.csproj
    - name: Build
      run: dotnet build src/MongrationDotNet/MongrationDotNet.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test dotnet build src/MongrationDotNet.Tests/MongrationDotNet.Tests.csproj --no-restore --verbosity normal
